/** Kenya counties (47) — same list used across player and operator forms. */
export const KENYA_COUNTIES = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
] as const;

export type KenyaCounty = (typeof KENYA_COUNTIES)[number];

/** Kenya administrative regions mapped from county (KNBS / former provinces). */
export const KENYA_COUNTY_TO_REGION: Record<KenyaCounty, string> = {
  Baringo: "Rift Valley",
  Bomet: "Rift Valley",
  Bungoma: "Western",
  Busia: "Western",
  "Elgeyo-Marakwet": "Rift Valley",
  Embu: "Eastern",
  Garissa: "North Eastern",
  "Homa Bay": "Nyanza",
  Isiolo: "Eastern",
  Kajiado: "Rift Valley",
  Kakamega: "Western",
  Kericho: "Rift Valley",
  Kiambu: "Central",
  Kilifi: "Coast",
  Kirinyaga: "Central",
  Kisii: "Nyanza",
  Kisumu: "Nyanza",
  Kitui: "Eastern",
  Kwale: "Coast",
  Laikipia: "Rift Valley",
  Lamu: "Coast",
  Machakos: "Eastern",
  Makueni: "Eastern",
  Mandera: "North Eastern",
  Marsabit: "Eastern",
  Meru: "Eastern",
  Migori: "Nyanza",
  Mombasa: "Coast",
  "Murang'a": "Central",
  Nairobi: "Nairobi",
  Nakuru: "Rift Valley",
  Nandi: "Rift Valley",
  Narok: "Rift Valley",
  Nyamira: "Nyanza",
  Nyandarua: "Central",
  Nyeri: "Central",
  Samburu: "Rift Valley",
  Siaya: "Nyanza",
  "Taita-Taveta": "Coast",
  "Tana River": "Coast",
  "Tharaka-Nithi": "Eastern",
  "Trans Nzoia": "Rift Valley",
  Turkana: "Rift Valley",
  "Uasin Gishu": "Rift Valley",
  Vihiga: "Western",
  Wajir: "North Eastern",
  "West Pokot": "Rift Valley",
};

export function getKenyaRegionForCounty(county: string | null | undefined): string | null {
  const trimmed = county?.trim();
  if (!trimmed) return null;
  return KENYA_COUNTY_TO_REGION[trimmed as KenyaCounty] ?? null;
}
